version: '3.8'

services:
  stats-app:
    image: stats-app:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: stats-app
    depends_on:
      - 'rabbitmq'
    env_file:
      - .env
    volumes:
      - .:/home/node/app
    entrypoint: ['/bin/sh', '-c', 'npx concurrently "npm run build:watch" "npm run local-start"']
