version: '3.8'

services:
  user-db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: user-db
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - './local-db:/var/lib/mysql'
  user-app:
    image: user-app:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: user-app
    ports:
      - '8000:3000'
    depends_on:
      - 'user-db'
    links:
      - 'user-db'
    env_file:
      - .env
    volumes:
      - .:/home/node/app
    entrypoint: ['/bin/sh', '-c', 'npx concurrently "npm run build:watch" "npm run local-start"']
  user-elasticsearch:
    image: elasticsearch:8.3.1
    container_name: user-elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.transport.ssl.enabled: false
    ports:
      - "9200:9200"
      - "9300:9300"
